[acm-terminal]
src.git = "https://github.com/twlz0ne/acm-terminal"
fetch.github = "twlz0ne/acm-terminal"

[wen]
src.git = "https://github.com/metaescape/Wen"
fetch.github = "metaescape/Wen"

[GodTian_Pinyin]
src.git = "https://github.com/whatbeg/GodTian_Pinyin"
fetch.github = "whatbeg/GodTian_Pinyin"
